import Navbar from "@/components/navbar";
import "../styles/global.css";
export const metadata = {
  title: "bookworm",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
